# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nbadw-util}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin Casey"]
  s.date = %q{2009-10-22}
  s.description = %q{Database models, migrations, and utilities for the New Brunswick Aquatic Data Warehouse}
  s.email = %q{casey.colin@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "LICENSE",
     "Rakefile",
     "lib/nbadw/util/copy_database_task.rb",
     "lib/nbadw/util/progress_bar.rb",
     "lib/sequel/adapters/jdbc/access.rb",
     "lib/sequel/adapters/shared/access.rb",
     "lib/sequel/jdbc_access_adapter.rb"
  ]
  s.homepage = %q{http://github.com/colincasey/nbadw}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{NB Aquatic Data Warehouse - Models and Database Utilities}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sequel>, [">= 3.5.0"])
    else
      s.add_dependency(%q<sequel>, [">= 3.5.0"])
    end
  else
    s.add_dependency(%q<sequel>, [">= 3.5.0"])
  end
end
